### ISSUE TITLE
Issue with notice

### ISSUE THREAD

**Issue by salexzee** [jaeming/RSVP#13]
I noticed a small issue with notices that I'll work on when I get a chance. When logged in, bar for `.notice` shows up empty and doesn't go away. Shouldn't be too difficult to fix. Also I need to make sure all notices have the same functionality. ALSO, I'll redo the notices to be styled in alignment with the theme.

**Comment by jaeming** [comment]
This is the first time I ever used the Rails scaffold command when generating (I think it might be the last time I use it) and I noticed it created a .notice in every view it scaffolded instead of just on in the main application view. So I'm not sure what's going on there but probably worth moving it to application. We'll want to move the nav bar and some other stuff to application as well at some point.

**Comment by salexzee** [comment]
I changed the notices removing the background and instead had the text turn green(theme green) and it fades out after 3 seconds. No more issue with the whole top being blocked while you're already signed in. Also, the nav bar is already in application. That was something I did last weekend. Well, technically it's in the header partial but same thing.
